// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB17UaJWFknRLDtA4rG0quGqAVEAHZgHFc',
    appId: '1:20838239483:android:0da8396935b022ce91345e',
    messagingSenderId: '20838239483',
    projectId: 'chatbuddy-7fe62',
    storageBucket: 'chatbuddy-7fe62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8iQF4FREqETlnd8Ro8EShooguUmj65No',
    appId: '1:20838239483:ios:46cdc3cc3063b27a91345e',
    messagingSenderId: '20838239483',
    projectId: 'chatbuddy-7fe62',
    storageBucket: 'chatbuddy-7fe62.appspot.com',
    iosBundleId: 'com.example.geminiChatAppTutorial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg0fx7t-jW0wzC_JMXFx4KeIT5IetwjbI',
    appId: '1:20838239483:web:9a7e9294f22b5e7891345e',
    messagingSenderId: '20838239483',
    projectId: 'chatbuddy-7fe62',
    authDomain: 'chatbuddy-7fe62.firebaseapp.com',
    storageBucket: 'chatbuddy-7fe62.appspot.com',
    measurementId: 'G-22HP1Y4BK5',
  );

}